export const scenaNames = {
  SEARCH_BY_NAME: "SEARCH_BY_NAME",
  getAbonentCard: "getAbonentCard",
  getWarningLetter: "getWarningLetter",
  new_abonent_request: "new_abonent_request",
  new_abonent_request_by_pinfl: "new_abonent_request_by_pinfl",
  updateElektrKod: "updateElektrKod",
  changeAbonentStreet: "changeAbonentStreet",
  createTarget: "createTarget",
  changePassword: "changePassword",
  abonentlarniGeozonagaBiriktirish: "abonentlarniGeozonagaBiriktirish",
  uploadWarningTozamakon: "uploadWarningTozamakon",
  sendWarningLettersByHybrid: "sendWarningLettersByHybrid",
  pochtaHarajatlariniTekshirish: "pochtaHarajatlariniTekshirish",
  generateProkraturaSudAriza: "generateProkraturaSudAriza",
  sudBuyruqlariYaratish: "sudBuyruqlariYaratish",
  ommaviyShartnomaBiriktirish: "ommaviyShartnomaBiriktirish",
  multiplyLivings: "multiplyLivings",
  guvohnomaKiritish: "guvohnomaKiritish",
  cancelGuvohnoma: "cancelGuvohnoma",
  confirmGuvohnoma: "confirmGuvohnoma",
  importPlanForInspectors: "importPlanForInspectors",
  connectPhoneNumber: "connectPhoneNumber",
  generateSBuyruq: "generateSBuyruq",
  connect_mfy_tg_group: "connect_mfy_tg_group",
  generateSavdoSanoatAriza: "generateSavdoSanoatAriza",
  personConfirm: "personConfirm",
  userToInspektor: "userToInspektor",
  updateAbonentDatesByPinfl: "updateAbonentDatesByPinfl",
  getSudMaterial: "getSudMaterial",
  addNotification: "addNotification",
  addNotificationPersonConfirm: "addNotificationPersonConfirm",
} as const;

export type SceneNames = keyof typeof scenaNames;
