// require("./yuqoriQarzdorliklar");
// require("./cleanCitySessionSaver");
// require("./updateArizalarStatus");
// require("./sendMFYIncomeReport");
// require("./sendPinflMfyReport");
require("./kunlikEtkReports");
// require("./kunlikPinflReports");
// require("./nazoratchilarKunlikTushum");
// require("./checkMailExpires");
require("../api/tozaMakon");
